<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TicketsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Within the year 2024
        $startDate = Carbon::create(2024, 1, 1, 0, 0, 0); // Start of 2024
        $endDate = Carbon::now(); // Current date in 2024

        DB::table('tickets')->insert([
            [
                'user_id' => 1,
                'building_number_id' => 1,
                'office_name_id' => 1,
                'priority_level' => 'High',
                'description' => 'Issue with the projector.',
                'file_path' => 'files/projector_issue.pdf',
                'status' => 'Open',
                'reason' => 'Urgent meeting',
                'purchase_parts' => 'None',
                'serial_number' => 123456789,
                'covered_under_warranty' => true,
                'initial_assessment' => 'On-Site',
                'action_performed' => 'Checked projector',
                'ictram_id' => null,
                'nicmu_id' => null,
                'mis_id' => 1,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 2,
                'building_number_id' => 2,
                'office_name_id' => 2,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'In Progress',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987654321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => null,
                'nicmu_id' => 2,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 3,
                'building_number_id' => 4,
                'office_name_id' => 4,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'Purchase Parts',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => 2,
                'nicmu_id' => null,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 4,
                'building_number_id' => 2,
                'office_name_id' => 3,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'Completed',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => null,
                'nicmu_id' => 3,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 5,
                'building_number_id' => 2,
                'office_name_id' => 2,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'Open',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => null,
                'nicmu_id' => null,
                'mis_id' => 1,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 6,
                'building_number_id' => 4,
                'office_name_id' => 1,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'In Progress',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 737685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => 3,
                'nicmu_id' => null,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 7,
                'building_number_id' => 3,
                'office_name_id' => 2,
                'priority_level' => 'High',
                'description' => 'Issue with the projector.',
                'file_path' => 'files/projector_issue.pdf',
                'status' => 'Closed',
                'reason' => 'Urgent meeting',
                'purchase_parts' => 'None',
                'serial_number' => 123456789,
                'covered_under_warranty' => true,
                'initial_assessment' => 'On-Site',
                'action_performed' => 'Checked projector',
                'ictram_id' => 4,
                'nicmu_id' => null,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 8,
                'building_number_id' => 2,
                'office_name_id' => 2,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'Completed',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987654321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => null,
                'nicmu_id' => 2,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 9,
                'building_number_id' => 4,
                'office_name_id' => 4,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'Open',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => 2,
                'nicmu_id' => null,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 1,
                'building_number_id' => 2,
                'office_name_id' => 3,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'Closed',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => null,
                'nicmu_id' => 3,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 2,
                'building_number_id' => 2,
                'office_name_id' => 2,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'In Progress',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 987685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => null,
                'nicmu_id' => null,
                'mis_id' => 1,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
            [
                'user_id' => 3,
                'building_number_id' => 4,
                'office_name_id' => 1,
                'priority_level' => 'Mid',
                'description' => 'Computer not starting.',
                'file_path' => 'files/computer_issue.pdf',
                'status' => 'Completed',
                'reason' => 'Routine checkup',
                'purchase_parts' => 'RAM',
                'serial_number' => 737685321,
                'covered_under_warranty' => false,
                'initial_assessment' => 'Shipped at Office',
                'action_performed' => 'Replaced RAM',
                'ictram_id' => 3,
                'nicmu_id' => null,
                'mis_id' => null,
                'created_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
                'updated_at' => $startDate->copy()->addDays(rand(0, $endDate->diffInDays($startDate))),
            ],
        ]);



        // // Array of sample data
        // $tickets = [ 
        //     [
        //         'building_number' => 'B1',
        //         'office_name' => 'Office A',
        //         'priority_level' => 'High',
        //         'description' => 'A high priority issue in Office A.',
        //         'status' => 'Open',
        //         'user_id' => 1,
        //         'file_path' => null,
        //         'ictram_id' => 1,
        //         // 'ictram_equipment_id' => 1,
        //         //'ictram_problem_id' => 1,
        //         // 'nicmu_id' => 1,
        //         // // 'nicmu_equipment_id' => 1,
        //         // // 'nicmu_problem_id' => 1,
        //         // // 'mis_request_type_id' => 1,
        //         // 'mis_id' => 1,
        //         // //  'mis_asname_id' => 1,
        //         'created_at' => Carbon::now()->subDays(rand(1, 14)),
        //         'updated_at' => Carbon::now()->subDays(rand(1, 14)),
        //     ],
        //     [
        //         'building_number' => 'B2',
        //         'office_name' => 'Office B',
        //         'priority_level' => 'Mid',
        //         'description' => 'A mid priority issue in Office B.',
        //         'status' => 'In Progress',
        //         'user_id' => 2,
        //         'file_path' => 'uploads/file2.pdf',
        //         // 'ictram_id' => 1,
        //         // // 'ictram_equipment_id' => 1,
        //         // //'ictram_problem_id' => 1,
        //         'nicmu_id' => 1,
        //         // 'nicmu_equipment_id' => 1,
        //         // 'nicmu_problem_id' => 1,
        //         // // 'mis_request_type_id' => 1,
        //         // 'mis_id' => 1,
        //         // //  'mis_asname_id' => 1,
        //         'created_at' => Carbon::now()->subDays(rand(1, 14)),
        //         'updated_at' => Carbon::now()->subDays(rand(1, 14)),
        //     ],
        //     [
        //         'building_number' => 'B3',
        //         'office_name' => 'Office C',
        //         'priority_level' => 'Low',
        //         'description' => 'A low priority issue in Office C.',
        //         'status' => 'Closed',
        //         'user_id' => 3,
        //         'file_path' => null,
        //         // 'ictram_id' => 1,
        //         // // 'ictram_equipment_id' => 1,
        //         // //'ictram_problem_id' => 1,
        //         // 'nicmu_id' => 1,
        //         // // 'nicmu_equipment_id' => 1,
        //         // // 'nicmu_problem_id' => 1,
        //         // 'mis_request_type_id' => 1,
        //         'mis_id' => 1,
        //         //  'mis_asname_id' => 1,
        //         'created_at' => Carbon::now()->subDays(rand(1, 14)),
        //         'updated_at' => Carbon::now()->subDays(rand(1, 14)),
        //     ],
        //     [
        //         'building_number' => 'B1',
        //         'office_name' => 'Office A',
        //         'priority_level' => 'High',
        //         'description' => 'A high priority issue in Office A.',
        //         'status' => 'Open',
        //         'user_id' => 1,
        //         'file_path' => null,
        //         'ictram_id' => 1,
        //         // 'ictram_equipment_id' => 1,
        //         //'ictram_problem_id' => 1,
        //         // 'nicmu_id' => 1,
        //         // // 'nicmu_equipment_id' => 1,
        //         // // 'nicmu_problem_id' => 1,
        //         // // 'mis_request_type_id' => 1,
        //         // 'mis_id' => 1,
        //         // //  'mis_asname_id' => 1,
        //         'created_at' => Carbon::now()->subDays(rand(1, 14)),
        //         'updated_at' => Carbon::now()->subDays(rand(1, 14)),
        //     ],
        //     [
        //         'building_number' => 'B2',
        //         'office_name' => 'Office B',
        //         'priority_level' => 'Mid',
        //         'description' => 'A mid priority issue in Office B.',
        //         'status' => 'In Progress',
        //         'user_id' => 2,
        //         'file_path' => 'uploads/file2.pdf',
        //         // 'ictram_id' => 1,
        //         // // 'ictram_equipment_id' => 1,
        //         // //'ictram_problem_id' => 1,
        //         'nicmu_id' => 1,
        //         // 'nicmu_equipment_id' => 1,
        //         // 'nicmu_problem_id' => 1,
        //         // // 'mis_request_type_id' => 1,
        //         // 'mis_id' => 1,
        //         // //  'mis_asname_id' => 1,
        //         'created_at' => Carbon::now()->subDays(rand(1, 14)),
        //         'updated_at' => Carbon::now()->subDays(rand(1, 14)),
        //     ],
        //     [
        //         'building_number' => 'B3',
        //         'office_name' => 'Office C',
        //         'priority_level' => 'Low',
        //         'description' => 'A low priority issue in Office C.',
        //         'status' => 'Closed',
        //         'user_id' => 3,
        //         'file_path' => null,
        //         // 'ictram_id' => 1,
        //         // // 'ictram_equipment_id' => 1,
        //         // //'ictram_problem_id' => 1,
        //         // 'nicmu_id' => 1,
        //         // // 'nicmu_equipment_id' => 1,
        //         // // 'nicmu_problem_id' => 1,
        //         // 'mis_request_type_id' => 1,
        //         'mis_id' => 1,
        //         //  'mis_asname_id' => 1,
        //         'created_at' => Carbon::now()->subDays(rand(1, 14)),
        //         'updated_at' => Carbon::now()->subDays(rand(1, 14)),
        //     ],
        // ];

        // // Insert the data into the database
        // DB::table('tickets')->insert($tickets);
    }
}
